###  Back Propogation Using Pytorch

y=x^2

In [2]:
import torch

In [3]:
x=torch.tensor(4.0, requires_grad=True)

In [4]:
x

tensor(4., requires_grad=True)

In [5]:
y=x**2
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
#### Back propogation y=2*x
y.backward()

In [7]:
print(x.grad)

tensor(8.)


In [8]:
lst=[[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]
torch_input=torch.tensor(lst,requires_grad=True)

In [9]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [10]:
### y=x**3+x**2
### y=3x**2+2x--->
y=torch_input**3+torch_input**2

In [11]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [12]:
z=y.sum()

In [13]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [14]:
z.backward()

In [15]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])